### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by 1sebsgithub1** [ouwei2013/medqa_colbert#1]
您好，我在huggingface上下载了您的与训练模型，在使用时遇到这个问题
AttributeError: 'BertForMaskedLM' object has no attribute 'search'
我是这么调用的不知道哪里出了问题？
`from transformers import AutoModelWithLMHead, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("./ir_chinese")
model = AutoModelWithLMHead.from_pretrained("./ir_chinese")

if __name__ == '__main__':
    query ='左手突然动不了，口嘴歪斜，这是什么病'
    results = model.search(query, k=10)
`

**Comment by ouwei2013** [comment]
你好，你可以打开那个库里面的app.py，看下这个文件里是怎么调用的。差不多是这样的：

def init():
searcher = None
with Run().context(RunConfig(nranks=1, experiment="medqa")):
    config = ColBERTConfig(
        root="./experiments",
    )
    searcher = Searcher(index="medqa_idx", config=config)
    

        
def search(query):
    results = searcher.search(query, k=5)
    responses=[]
    # idx = 0 
    for passage_id, _, _ in zip(*results):
          responses.append(searcher.collection[passage_id])
        #   idx = idx+1
    return responses
